### ISSUE TITLE
do-release-upgrade (request for a short how-to)

### ISSUE THREAD

**Issue by tinhoff** [Sithuk/ubuntu-server-zfsbootmenu#11]
Could someone write down the key bullet points for a safe 22.04 -> 22.10 upgrade?

0. snapshot everything
1. cloning rpool/ROOT/ubuntu-whatever

But what then? Is there anything needs to be done in grub/dracut or must happen in some specific order, or literally just: reboot & automatically I can chose to boot from the new clone, can perform a normal do-release-upgrade and, if system is working as expected: be happy. If not, boot next time again from the "old" root pool and everything will be fine as before the do-release-upgrade attempt ?!

Don't want to mess the weekend and maybe, some kind soul exactly know what todo and could tell?

[edit] coming from a system installed with this script (22.04)

**Comment by Sithuk** [comment]
Try the following to upgrade.
sudo pyznap snap ##Take a pre-upgrade snapshot
sudo apt update
sudo apt upgrade
sudo sed -i 's,=lts,=normal,' /etc/update-manager/release-upgrades
sudo do-release-upgrade

You should be able to do the following to rollback to the snapshot if the upgrade does not work.
Reboot and enter zfsbootmenu
Select the boot environment and press Ctrl+S to show the snapshots.
Select the pre-upgrade snapshot and choose one of the following options.
i) Press Enter to create a duplicate. Zfsbootmenu will create a duplicate boot environment from the snapshot that is entirely independent of the upgraded boot environment and its snapshots. You can then boot into it and the system will be as it was pre-upgrade. The down side of a duplicate is that you will not have all the earlier snapshots.
ii) Press Ctrl+X to "clone and promote". Zfsbootmenu will create a new boot environment from the snapshot that will have all the snapshot history.
The zfsbootmenu authors recommend the "clone and promote" option to rollback. Zfsbootmenu does not provide any tools to delete an unused boot environment. You can use zectl if you would like to do that. You will need to compile and install it as I don't think it is available in any ppas.
https://github.com/johnramsden/zectl

I recommend testing any changes out in a virtual machine first before rolling them out in a production environment.

**Comment by Sithuk** [comment]
I ran a test upgrade from 22.04 to 22.10 in a virtual machine. The upgrade seem to work, but it looks like zfsbootmenu may also need to be re-compiled. Otherwise you run into the following zfsbootmenu bug when re-creating a new zfsbootmenu efi file. You can just avoid running "generate-zbm" after the upgrade and your system should work, but you run the risk of a non-booting system if you ever run generate-zbm.
https://github.com/zbm-dev/zfsbootmenu/issues/335

You can extract the code to compile zfsbootmenu from the script in your new system. I'll have a think about how to make upgrading easier. I don't think pyznap is in the ubuntu ppas either, so that may also need to be re-compiled following an upgrade, although it seems to work fine after upgrading from 22.04 to 22.10.

**Comment by Sithuk** [comment]
The fix for the zfsbootmenu issue has been approved (but not yet merged).
https://github.com/zbm-dev/zfsbootmenu/pull/349

Once it has been merged, you should re-install zfsbootmenu in your upgraded system. Your system will work with the old zfsbootmenu created EFI file, but at some point you may want to update zfsbootmenu and that will need the fix. Remember to wait for the fix to be merged first before you reinstall zfsbootmenu from git (or you could implement the fixes manually by editing the cloned git master, before you run "make core dracut").
--
cd /tmp
git clone 'https://github.com/zbm-dev/zfsbootmenu.git'
cd zfsbootmenu
make core dracut
sed \
		  -e 's,ManageImages:.*,ManageImages: true,' \
		  -e 's@ImageDir:.*@ImageDir: /boot/efi/EFI/ubuntu@' \
		  -e 's,Versions:.*,Versions: false,' \
		  -i /etc/zfsbootmenu/config.yaml
update-initramfs -c -k all
generate-zbm --debug

**Comment by tinhoff** [comment]
Thanks for this amazing support / help / investigation!

**Comment by Sithuk** [comment]
You're welcome. The upstream fix is shown below.
https://github.com/zbm-dev/zfsbootmenu/pull/349/files

The following two commands will apply the upstream fix. Run them before you run "sudo make core dracut"
sudo sed -i 's,echo udev-rules,echo bash udev-rules,' /tmp/zfsbootmenu/dracut/module-setup.sh
sudo sed -i 's,plymouth \",plymouth dash \",' /tmp/zfsbootmenu/etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf
